#%RAML 1.0
---
title: CTC Traders
description: The public API to allow traders to submit and receive Common Transit Convention Phase 5 (IE) messages
protocols: [ HTTPS ]
baseUri: https://common-transit-convention-traders.hmrc.gov.uk/
version: 2.0

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Percent-encoding of parameters in request URLs
   content: !include docs/percent-encoding.md
 - title: Push Pull notifications
   content: !include docs/pushPull.md
 - title: Errors
   content: !include docs/errors.md

mediaType: [ application/json, application/xml ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  contentXmlHeader:
    headers:
      Content-Type:
        description: Specifies the format of the request body, which must be XML, using UTF-8 character encoding.
        type: string
        required: true
        example: application/xml
  contentXmlJsonHeader:
    headers:
      Content-Type:
        description: Specifies the format of the request body, which must be XML or JSON, using UTF-8 character encoding.
        type: string
        required: true
        example: application/xml
  acceptJsonHeader:
    headers:
      Accept:
        description: |
          Specifies the response format, which must be JSON, and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
        type: string
        required: true
        example: application/vnd.hmrc.2.0+json
  acceptSingleMessageGetHeader:
    headers:
      Accept:
        description: |
          Specifies the response format, which must be JSON or JSON+XML, and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
          
          Acceptable values are `application/vnd.hmrc.2.0+json` or `application/vnd.hmrc.2.0+json-xml`.
        type: string
        required: true
        example: application/vnd.hmrc.2.0+json-xml
  acceptHeaderInvalid:
    responses:
      406:
        body:
          application/json:
            type: types.errorResponse
            examples:
              badRequest:
                description: The accept header is missing or invalid.
                value:
                  code : ACCEPT_HEADER_INVALID
  requestTooLarge:
    responses:
      413:
        body:
          application/json:
            type: types.errorResponse
            examples:
              requestEntityTooLarge:
                description: The request body is too large.
                value:
                  code: REQUEST_ENTITY_TOO_LARGE
  schemaValidation:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              schemaValidation:
                description: The request body failed schema validation.
                value:
                  code: SCHEMA_VALIDATION

/customs/transits/movements:
  /departures:
    post:
      displayName: Send a declaration data message
      description: |
        Send a transit declaration to the Customs Office of Departure to notify it that you wish to carry out a transit operation.

        This request is also called an ‘Declaration Data’ E_DEC_DAT (IE015) message.

        A successful response will contain a URI and a departure ID for the notification, which you can use to retrieve messages related to the movement.

        It will also contain an embedded request ID, box ID and box name, which you can use to match this movement to any messages received from the Push Pull Notifications API.

        **Note:** If an Economic Operators Registration and Identification (EORI) number has not been assigned to you, an HTTP 403 Forbidden error is returned.
      is: 
        - contentXmlJsonHeader
        - acceptJsonHeader
        - requestTooLarge
        - schemaValidation
      (annotations.scope): "common-transit-convention-traders"
      securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
      responses:
        202:
          body:
            application/json:
              description: JSON payload
              example: |
                {
                  "_links":{
                    "self":{
                      "href": "/customs/transits/movements/departures/62fb8f33d233578e"
                    },
                    "messages":{
                      "href": "/customs/transits/movements/departures/62fb8f33d233578e/messages"
                    }
                  }
                }
    get:
      displayName: Get all cached departures
      description: |
        Retrieve all departure declarations sent to the Customs Office of Departure within the past 31 days.

        You can filter for departure declarations updated after a specific date and time.

        Movements older than 31 days and their related messages are archived and cannot be returned by the API.

        A successful response will include a Movement Reference Number (MRN) only after it has been allocated to a movement.
        
        **Note:** You can view a transit movement only if your Economic Operators Registration and Identification (EORI) number matches the EORI number that created the transit declaration for that movement. Your EORI number is part of the bearer token that you use for API authentication.
      is:
        - acceptJsonHeader
        - acceptHeaderInvalid
      queryParameters:
        updatedSince:
          required: false
          type: datetime
          description: This is an optional query parameter that you can use to filter for departure declarations updated after a specific date and time.
          example: 2021-06-21T09:00+00:00
      (annotations.scope): "common-transit-convention-traders"
      securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
      responses:
        200:
          body:
            application/json:
              description: JSON payload
              example: |
                {
                  "_links":{
                    "self":{
                      href":"/customs/transits/movements/departures"
                    }
                  },
                  departures":[
                   "_links":{
                      "self":{
                        "href":"/customs/transits/movements/departures/6365135ba5e821ee"
                      },
                      "messages":{
                        "href":"/customs/transits/movements/departures/6365135ba5e821ee/messages"
                      }
                    },
                    "id":"6365135ba5e821ee",
                    "movementReferenceNumber":"ABC123",
                    "created":"2022-11-10T15:32:51.459Z",
                    "updated":"2022-11-10T15:32:51.459Z",
                    "enrollmentEORINumber": "GB1234567890",
                    "movementEORINumber": "GB1234567890"
                  ]
                }
    /{departureId}:
      get:
        displayName: Get a cached departure for a departure ID
        description: |
          Retrieve a specific departure declaration sent to the Customs Office of Departure within the past 31 days.

          Movements older than 31 days and their related messages are archived and cannot be returned by the API.

          A successful response will include a Movement Reference Number (MRN) only after it has been allocated to a movement.

          **Note:** You can view a transit movement only if your Economic Operators Registration and Identification (EORI) number matches the EORI number that created the transit declaration for that movement. Your EORI number is part of the bearer token that you use for API authentication.
        is:
          - acceptJsonHeader
          - acceptHeaderInvalid
        (annotations.scope): "common-transit-convention-traders"
        securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
        responses:
          200:
            body:
              application/json:
                description: JSON payload
                example: |
                    {
                      "_links":{
                        "self":{
                          "href":"/customs/transits/movements/departures/6365135ba5e821ee"
                        },
                        "messages":{
                          "href":"/customs/transits/movements/departures/6365135ba5e821ee/messages"
                        }
                      },
                      "id":"6365135ba5e821ee",
                      "movementReferenceNumber":"ABC123",
                      "created":"2022-11-10T15:32:51.459Z",
                      "updated":"2022-11-10T15:32:51.459Z",
                      "enrollmentEORINumber": "GB1234567890",
                      "movementEORINumber": "GB1234567890"
                    }
          404:
            description: The specified departure does not exist, has been archived or is not available to the EORI number.
      /messages:
        get:
          displayName: Get all cached messages related to a departure
          description: |
            Retrieve all messages related to a specific departure declaration sent to the Customs Office of Departure within the past 31 days.

            You can filter for departure declarations received after a specific date and time.

            Movements older than 31 days are archived, so any messages to related to them cannot be returned by the API.

            A successful response will include a Movement Reference Number (MRN) only after it has been allocated to a movement.

            **Note:** You can view a transit movement only if your Economic Operators Registration and Identification (EORI) number matches the EORI number that created the transit declaration for that movement. Your EORI number is part of the bearer token that you use for API authentication.
          is:
            - acceptJsonHeader
            - acceptHeaderInvalid
          queryParameters:
            receivedSince:
              required: false
              type: datetime
              description: This is an optional query parameter that you can use to filter for departure declarations received after a specific date and time.
              example: 2021-06-21T09:00+00:00
          (annotations.scope): "common-transit-convention-traders"
          securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
          responses:
            200:
              body:
                application/json:
                  description: JSON payload
                  example: |
                    {
                      "_links":{
                        "self":{
                          "href":"/customs/transits/movements/departures/6365135ba5e821ee/messages"
                        },
                        "departure":{
                          "href":"/customs/transits/movements/departures/6365135ba5e821ee"
                        }
                      },
                      "messages":[
                        {
                          "_links":{
                            "self":{
                              "href":"/customs/transits/movements/departures/6365135ba5e821ee/message/634982098f02f00a"
                            },
                            "departure":{
                              "href":"/customs/transits/movements/departures/6365135ba5e821ee"
                            }
                          },
                          "id":"634982098f02f00a",
                          "departureId":"6365135ba5e821ee",
                          "received":"2022-11-10T15:32:51.459Z",
                          "type":"IE015"
                        }
                      ]
                    }
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    notFound:
                      description: The specified departure does not exist, has been archived or is not available to the EORI number.
                      value:
                        code: NOT_FOUND
        post:
          displayName: Send a message related to a departure
          description: |
            Send a message to the Customs Office of Departure about a departure.
    
            For example, if you want to cancel a ‘Declaration Data’ E_DEC_DAT (IE015) message, you must send a ‘Declaration Invalidation Request’ E_DEC_INV (IE014) message to the Office of Departure.
    
            A successful response will contain a URI and a message ID related to the departure, which you can use to retrieve the message status.
    
            **Note:** If an Economic Operators Registration and Identification (EORI) number has not been assigned to you, an HTTP 403 Forbidden error is returned.
          is:
            - contentXmlJsonHeader
            - acceptJsonHeader
            - requestTooLarge
          (annotations.scope): "common-transit-convention-traders"
          securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
          responses:
            202:
              body:
                application/json:
                  description: JSON payload
                  example: |
                    {
                      "_links": {
                        "self": {
                          "href": "/customs/transits/movements/departures/6365135ba5e821ee/messages/634982098f02f00a"
                        },
                        "departure": {
                          "href": "/customs/transits/movements/departures/6365135ba5e821ee"
                        }
                      }
                    }
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    notFound:
                      description: The specified departure does not exist, has been archived or is not available.
                      value:
                        code: NOT_FOUND
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    badRequest:
                      description: The departure message type is not available within XML or the message failed schema validation.
                      value:
                        code: BAD_REQUEST
        /{messageId}:
          get:
            displayName: Get a cached message related to a departure and message ID
            description: |
              Retrieve all messages related to a specific departure and message ID that have been received within the past 31 days.

              For example, this could include ‘Declaration rejected’ or Movement Reference Number (MRN) allocated messages.

              Movements older than 31 days and their related messages are archived and cannot be returned by the API.
              
              The response can be returned in one of the following formats based on the provided `Accept` header:
        
              * `application/vnd.hmrc.2.0+json-xml`: JSON-wrapped XML, where the message is provided as an XML string sent as part of JSON payload containing other metadata.
              * `application/vnd.hmrc.2.0+json`: JSON, where the message is provided as a sub-document sent as part of a JSON payload containing other metadata.
               
              **Note:** You can view a transit movement only if your Economic Operators Registration and Identification (EORI) number matches the EORI number that created the transit declaration for that movement. Your EORI number is part of the bearer token that you use for API authentication.
            is:
              - acceptSingleMessageGetHeader
              - acceptHeaderInvalid
            (annotations.scope): "common-transit-convention-traders"
            securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
            responses:
              200:
                body:
                  application/json+xml:
                    description: JSON+XML payload
                    example: |
                      {
                        "_links":{
                          "self":{
                            "href": "/customs/transits/movements/departures/62f4ebbbf581d4aa/messages/62f4ebbb765ba8c2"
                          },
                          "departure":{
                            "href": "/customs/transits/movements/departures/62f4ebbbf581d4aa"
                          }
                        },
                        "id": "62f4ebbb765ba8c2",
                        "departureId": "62f4ebbbf581d4aa",
                        "received": "2022-08-11T11:44:59.83705",
                        "type": "IE015",
                        "body": "<ncts:CC015C PhaseID=\"NCTS5.0\" xmlns:ncts=\"http://ncts.dgtaxud.ec\">...</ncts:CC015C>"
                      }
                  application/json:
                    description: JSON payload
                    example: |
                      {
                        "_links":{
                          "self":{
                            "href": "/customs/transits/movements/departures/62f4ebbbf581d4aa/messages/62f4ebbb765ba8c2"
                          },
                          "departure":{
                            "href": "/customs/transits/movements/departures/62f4ebbbf581d4aa"
                          }
                        },
                        "departure":{
                          "id": "/customs/transits/movements/departures/62f4ebbbf581d4aa"
                        },
                        "id": "/customs/transits/movements/departures/62f4ebbbf581d4aa/messages/62f4ebbb765ba8c2",
                        "received": "2022-08-11T11:44:59.83705",
                        "messageType": "IE015",
                        "body":{
                          "n1.CC015C": {
                            "@PhaseID": "NCTS5.0",
                            ...
                          }
                        }
                      }
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: The specified message does not exist, has been archived or is not available to the EORI number.
                        value:
                          code: NOT_FOUND
  /arrivals:
    post:
      displayName: Send an arrival notification message
      description: |
        Notify the Customs Office of Destination that a transit movement has arrived at its final destination.

        This request is also called an ‘Arrival Notification’ E_ARR_NOT (IE007) message.

        A successful response will contain a URI, which you can use to retrieve the message status.

        **Note:** If an Economic Operators Registration and Identification (EORI) number has not been assigned to you, an HTTP 403 Forbidden error is returned.
      is:
        - contentXmlHeader
        - acceptJsonHeader
        - requestTooLarge
        - schemaValidation
      (annotations.scope): "common-transit-convention-traders"
      securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
      responses:
        202:
          body:
            application/json:
              description: JSON payload
              example: |
                {
                  "_links":{
                    "self":{
                      "href": "/customs/transits/movements/arrivals/62fb8f33d233578e"
                    },
                    "messages":{
                      "href": "/customs/transits/movements/arrivals/62fb8f33d233578e/messages"
                    }
                  }
                }
    get:
      displayName: Get all cached arrivals
      description: |
        Retrieve all arrivals that have been updated within the past 31 days.

        You can filter for arrivals updated after a specific date and time.

        Movements older than 31 days and their related messages are archived and cannot be returned by the API.

        **Note:** You can view a transit movement only if your Economic Operators Registration and Identification (EORI) number matches the EORI number that created the transit declaration for that movement. Your EORI number is part of the bearer token that you use for API authentication.
      is:
        - acceptJsonHeader
        - acceptHeaderInvalid
      queryParameters:
        updatedSince:
          required: false
          type: datetime
          description: This is an optional query parameter that you can use to filter for arrivals updated after a specific date and time.
          example: 2021-06-21T09:00+00:00
      (annotations.scope): "common-transit-convention-traders"
      securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
      responses:
        200:
          body:
            application/json:
              description: JSON payload
              example: |
                {
                  "_links": {
                    "self": {
                      "href": "/customs/transits/movements/arrivals"
                    }
                  },
                  "arrivals": [
                    {
                      "_links": {
                        "self": {
                          "href": "/customs/transits/movements/arrivals/63651574c3447b12"
                        },
                        "messages": {
                          "href": "/customs/transits/movements/arrivals/63651574c3447b12/messages"
                        }
                      },
                      "id": "63651574c3447b12",
                      "movementReferenceNumber": "27WF9X1FQ9RCKN0TM3",
                      "created": "2022-11-04T13:36:52.332Z",
                      "updated": "2022-11-04T13:36:52.332Z",
                      "enrollmentEORINumber": "9999912345",
                      "movementEORINumber": "ezv3Z"
                    },
                    {
                      "_links": {
                        "self": {
                          "href": "/customs/transits/movements/arrivals/6365135ba5e821ee"
                        },
                        "messages": {
                          "href": "/customs/transits/movements/arrivals/6365135ba5e821ee/messages"
                        }
                      },
                      "id": "6365135ba5e821ee",
                      "movementReferenceNumber": "27WF9X1FQ9RCKN0TM3",
                      "created": "2022-11-04T13:27:55.522Z",
                      "updated": "2022-11-04T13:27:55.522Z",
                      "enrollmentEORINumber": "9999912345",
                      "movementEORINumber": "ezv3Z"
                    }
                  ]
                }
    /{arrivalId}:
      get:
        displayName: Get a cached arrival for an arrival ID
        description: |
          Retrieve a specific arrival notification sent to the Customs Office of Destination within the past 31 days.

          Movements older than 31 days and their related messages are archived and cannot be returned by the API.

          **Note:** You can view a transit movement only if your Economic Operators Registration and Identification (EORI) number matches the EORI number that created the transit declaration for that movement. Your EORI number is part of the bearer token that you use for API authentication.
        is:
          - acceptJsonHeader
          - acceptHeaderInvalid
        (annotations.scope): "common-transit-convention-traders"
        securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
        responses:
          200:
            body:
              application/json:
                description: JSON payload
                example: |
                    {
                      "_links":{
                        "self":{
                          "href":"/customs/transits/movements/arrivals/6365135ba5e821ee"
                        },
                        "messages":{
                          "href":"/customs/transits/movements/arrivals/6365135ba5e821ee/messages"
                        }
                      },
                      "id":"6365135ba5e821ee",
                      "movementReferenceNumber":"ABC123",
                      "created":"2022-11-10T15:32:51.459Z",
                      "updated":"2022-11-10T15:32:51.459Z",
                      "enrollmentEORINumber": "GB1234567890",
                      "movementEORINumber": "GB1234567890"
                    }
          404:
            description: The specified departure does not exist, has been archived or is not available to the EORI number.
      /messages:
         get:
            displayName: Get all cached messages related to an arrival
            description: |
              Retrieve all messages related to a specific arrival that have been received within the past 31 days.

              You can filter for arrivals received after a specific date and time.

              Movements older than 31 days are archived, so any messages related to them cannot be returned by the API.

              **Note:** You can view a transit movement only if your Economic Operators Registration and Identification (EORI) number matches the EORI number that created the transit declaration for that movement. Your EORI number is part of the bearer token that you use for API authentication.
            is:
              - acceptJsonHeader
              - acceptHeaderInvalid
            queryParameters:
              receivedSince:
                required: false
                type: datetime
                description: This is an optional query parameter that you can use to filter for arrivals received after a specific date and time.
                example: 2021-06-21T09:00+00:00
            (annotations.scope): "common-transit-convention-traders"
            securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
            responses:
              200:
                body:
                   application/json:
                     description: JSON payload
                     example: |
                       {
                          "_links":{
                             "self":{
                                "href":"/customs/transits/movements/arrivals/63498209a2d89ad8/messages"
                             },
                             "arrival":{
                                "href":"/customs/transits/movements/arrivals/63498209a2d89ad8"
                             }
                          },
                          "messages":[
                             {
                                "_links":{
                                    "self":{
                                       "href":"/customs/transits/movements/arrivals/63498209a2d89ad8/messages/634982098f02f00a"
                                    },
                                    "arrival":{
                                       "href":"/customs/transits/movements/arrivals/63498209a2d89ad8"
                                    }
                                },
                                "id":"634982098f02f00a",
                                "arrivalId":"63498209a2d89ad8",
                                "received":"2022-11-10T15:32:51.459Z",
                                "type":"IE007"
                             }
                          ]
                       }
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: The specified arrival does not exist, has been archived or is not available to the EORI number.
                        value:
                          code: NOT_FOUND
        /{messageId}:
          get:
            displayName: Get a cached message related to a arrival and message ID
            description: |
              Retrieve all messages related to a specific arrival and message ID that have been received within the past 31 days.

              For example, this could include ‘Declaration rejected’ or Movement Reference Number (MRN) allocated messages.

              Movements older than 31 days and their related messages are archived and cannot be returned by the API.

               The response can be returned in one of the following formats based on the provided `Accept` header:

               * `application/vnd.hmrc.2.0+json-xml`: JSON-wrapped XML, where the message is provided as an XML string sent as part of JSON payload containing other metadata.
               * `application/vnd.hmrc.2.0+json`: JSON, where the message is provided as a sub-document sent as part of a JSON payload containing other metadata.

               **Note:** You can view a transit movement only if your Economic Operators Registration and Identification (EORI) number matches the EORI number that created the transit declaration for that movement. Your EORI number is part of the bearer token that you use for API authentication.
            is:
              - acceptSingleMessageGetHeader
              - acceptHeaderInvalid
            (annotations.scope): "common-transit-convention-traders"
            securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
            responses:
              200:
                body:
                  application/json+xml:
                    description: JSON+XML payload
                    example: |
                      {
                        "_links":{
                          "self":{
                            "href": "/customs/transits/movements/arrivals/62f4ebbbf581d4aa/messages/62f4ebbb765ba8c2"
                          },
                          "arrival":{
                            "href": "/customs/transits/movements/arrivals/62f4ebbbf581d4aa"
                          }
                        },
                        "id": "62f4ebbb765ba8c2",
                        "arrivalId": "62f4ebbbf581d4aa",
                        "received": "2022-08-11T11:44:59.83705",
                        "type": "IE007",
                        "body": "<ncts:IE007 PhaseID=\"NCTS5.0\" xmlns:ncts=\"http://ncts.dgtaxud.ec\">...</ncts:IE007>"
                      }
                  application/json:
                    description: JSON payload
                    example: |
                      {
                        "_links":{
                          "self":{
                            "href": "/customs/transits/movements/arrivals/62f4ebbbf581d4aa/messages/62f4ebbb765ba8c2"
                          },
                          "arrival":{
                            "href": "/customs/transits/movements/arrivals/62f4ebbbf581d4aa"
                          }
                        },
                        "id": "62f4ebbb765ba8c2",
                        "arrivalId": "62f4ebbbf581d4aa",
                        "received": "2022-08-11T11:44:59.83705",
                        "type": "IE007",
                        "body":{
                          "n1.CC007C": {
                            "@PhaseID": "NCTS5.0",
                            ...
                          }
                        }
                      }
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      notFound:
                        description: The specified message does not exist, has been archived or is not available to the EORI number.
                        value:
                          code: NOT_FOUND