#%RAML 1.0
---
title: CTC Traders

protocols: [ HTTPS ]
baseUri: https://common-transit-convention-traders.hmrc.gov.uk/
version: v0.1

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: application/xml

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/movements:
  /arrivals:
    post:
      displayName: Send an arrivals notification
      description: |
        Send a message to let the Office of Destination know that the goods have arrived. This message will be sent when the goods reach their final destination. It is also called an E_ARR_NOT (IE007).      is: [headers.acceptHeader]
      (annotations.scope): "common-transit-convention-traders"
      securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
      responses:
        204:
          body:
            application/xml:
              description: Valid XML Payload
              example: |
                <IE007>
                </IE007>
    get:
      displayName: Pull all arrival notifications
      description: |
        Pull all arrival messages sent to the Office of Destination in the last 28 days.
      is: [headers.acceptHeader]
      (annotations.scope): "common-transit-convention-traders"
      securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
      responses:
        200:
          body:
            application/xml:
              description: Valid XML Payload
              example: |
                <transactions>
                  <IE007>
                  </IE007>
                </transactions>
    /{transactionId}:
      get:
        displayName: Pull an arrival notification for a transaction ID
        description: |
          Pull a specific arrival message which was sent to the Office of Destination in the last 28 days. Any arrival notifications that are more than 28 days old will be archived. Archived notifications will be return a “not found” message.
        is: [headers.acceptHeader]
        (annotations.scope): "common-transit-convention-traders"
        securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
        responses:
          200:
            body:
              application/xml:
                description: Valid XML Payload
                example: |
                  <IE007></IE007>
          404:
            description: when arrival movement does not exist, has been archived or is not available to the eori.
      /messages:
        get:
          displayName: Pull all messages relating to an arrival movement
          description: |
            Pull all messages sent in the last 28 days relating to an arrival movement. You will only be able to retrieve these messages if you have the EORI associated with the arrival movement.
          responses:
            200:
              body:
                application/xml:
                  description: Valid XML Payload
                  example: |
                    <123></123>
            404:
              description: when the arrival movement does not exist, has been archived or is not available to the eori.
        /{messageId}:
          get:
            displayName: Pull a message relating to an arrival movement and message ID
            description: |
              Pull a message relating to a specific arrival movement and message ID. For example, this could include messages about route diversions or unloading permissions. Any messages more than 28 days old will be archived. Archived messages will be return a “not found” message.
            responses:
              200:
                body:
                  application/xml:
                    description: Valid XML Payload
                    example: |
                      <CC058A></CC058A>
              404:
                description: when message does not exist, has been archived or is not available to the eori.
