#%RAML 1.0
---
title: CTC Traders
description: The public API to allow traders to submit and receive Common Transit Convention (IE) messages
protocols: [ HTTPS ]
baseUri: https://common-transit-convention-traders.hmrc.gov.uk/
version: 1.0

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Percent-encoding of parameters in request URLs
   content: !include docs/percent-encoding.md
 - title: Push Pull notifications
   content: !include docs/pushPull.md
 - title: Errors
   content: !include docs/errors.md

mediaType: [ application/json, application/xml ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  contentXmlHeader:
    headers:
      Content-Type:
        description: Specifies the format of the request body, which must be XML.
        type: string
        required: true
        example: application/xml
  acceptHeaderInvalid:
    responses:
      406:
        body:
          application/json:
            type: types.errorResponse
            examples:
              badRequest:
                description: The accept header is missing or invalid
                value:
                  code : ACCEPT_HEADER_INVALID

/customs/transits/movements:
  /arrivals:
    post:
      displayName: Send an Arrival Notification message
      description: |
        Send a notification to let the office at destination know that the goods have arrived.

        This notification will be sent when the goods reach their final destination. It is also called an E_ARR_NOT (IE007).

        The response will contain a URI and arrival ID for the Arrival Notification. This will allow you to get the message status.

        The response will also contain an embedded requestId, boxId and boxName which will allow you to match this movement to any messages received via the Push Pull Notifications Service.

        If the user is not enrolled for an Economic Operator Registration and Identification number, they will receive an HTTP 403 Forbidden status.
      is: [contentXmlHeader]
      (annotations.scope): "common-transit-convention-traders"
      securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
      responses:
        202:
          body:
            application/json:
              description: JSON Payload
              example: |
                {
                  "_links": {
                    "self": {
                      "href": "/customs/transits/movements/arrivals/1"
                    }
                  },
                  "arrivalId": "1",
                  "messageType": "IE007",
                  "body": "<CC007A>...</CC007A>",
                  "_embedded":
                  {
                    "notifications":{
                      "boxId":"1234-5678-abcd-def",
                      "requestId":"/customs/transits/movements/arrivals/1",
                      "boxName":"customs/transits##1.0##notificationUrl"
                    }
                  }
                }
    get:
      displayName: Get all Movement Arrivals
      description: |
        Get all Movement Arrivals.

        You may opt to filter this list of Arrivals so that you only receive Movement Arrivals that have been updated since a specified date and time.

        Any Movement Arrivals more than 28 days old will have been archived along with their related messages. Archived movements will return an HTTP 404 Not Found status. You will only be able to retrieve these messages if you have the correct Economic Operator Registration and Identification (EORI) number for that Movement Arrival.
      is:
        - headers.acceptHeader
        - acceptHeaderInvalid
      queryParameters:
        updatedSince:
          required: false
          type: datetime
          description: This is an optional filtering parameter. It allows you to request only the Movement Arrivals which have been updated since the date and time you have given us.
          example: 2021-06-21T09:00+00:00
      (annotations.scope): "common-transit-convention-traders"
      securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
      responses:
        200:
          body:
            application/json:
              description: JSON Payload
              example: |
                {
                  "_links": {
                    "self": {
                      "href": "/customs/transits/movements/arrivals"
                    }
                  },
                  "_embedded": {
                    "arrivals": [
                      {
                        "id": "1",
                        "created": "2020-02-02T02:02:02",
                        "updated": "2020-02-02T02:02:02",
                        "movementReferenceNumber": "MRN",
                        "_links": {
                          "self": {
                            "href": "/customs/transits/movements/arrivals/1"
                          },
                          "messages": {
                            "href": "/customs/transits/movements/arrivals/1/messages"
                          }
                        }
                      },
                      {
                        "id": "2",
                        "created": "2020-02-04T02:02:02",
                        "updated": "2020-02-04T02:02:02",
                        "movementReferenceNumber": "MRN",
                        "_links": {
                          "self": {
                            "href": "/customs/transits/movements/arrivals/2"
                          },
                          "messages": {
                            "href": "/customs/transits/movements/arrivals/2/messages"
                          }
                        }
                      }
                    ],
                    "retrievedArrivals": 2,
                    "totalArrivals": 2
                  }
                }

    /{arrivalId}:
      uriParameters:
        arrivalId:
          description: The arrival ID specifying the arrival to return
          type: string
          example: "1"
          required: true
      put:
        displayName: Resubmit an Arrival Notification message
        description: |
          Resubmit an Arrival Notification to let the office at destination know that the goods have arrived. This message will be sent when the goods reach their final destination. It is also called an E_ARR_NOT (IE007).

          The response will contain an arrival ID for the Arrival Notification. This will allow you to get the message status.

          If the user is not enrolled for an Economic Operator Registration and Identification number, they will receive an HTTP 403 Forbidden status.
        is: [contentXmlHeader]
        (annotations.scope): "common-transit-convention-traders"
        securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
        responses:
          202:
            body:
              application/json:
                description: JSON Payload
                example: |
                  {
                    "_links": {
                      "self": {
                        "href": "/customs/transits/movements/arrivals/1"
                      }
                    },
                    "arrivalId": "1",
                    "messageType": "IE007",
                    "body": "<CC007A>...</CC007A>"
                  }

      get:
        displayName: Get a Movement Arrival for an arrival ID
        description: |
         Get a specific Movement Arrival. Any Movement Arrivals more than 28 days old will be haven archived along with their related messages. Archived movements will return an HTTP 404 Not Found status.

          You will only be able to retrieve these messages if you have the correct Economic Operator Registration and Identification (EORI) number for that Movement Arrival.
        is:
          - headers.acceptHeader
          - acceptHeaderInvalid
        (annotations.scope): "common-transit-convention-traders"
        securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
        responses:
          200:
            body:
              application/json:
                description: JSON Payload
                example: |
                  {
                    "id": "1",
                    "created": "2020-10-10T10:10:10",
                    "updated": "2020-12-12T12:12:12",
                    "movementReferenceNumber": "MRN",
                    "_links": {
                      "self": {
                        "href": "/customs/transits/movements/arrivals/1"
                      },
                      "messages": {
                        "href": "/customs/transits/movements/arrivals/1/messages"
                      }
                    }
                  }
          404:
            description: When a Movement Arrival does not exist, has been archived or is not available to the EORI number.
      /messages:
        post:
          displayName: Send a message related to an Movement Arrival
          description: |
            Send a message to the office at destination. For example, an Unloading Remarks message, otherwise known as E_ULD_REM (IE044), to let them know that the goods have been unloaded.

            The response will contain a URI and message ID for the message related to the Movement Arrival. This will allow you to get the message status.

            If the user is not enrolled for an Economic Operator Registration and Identification number, they will receive an HTTP 403 Forbidden status.
          is: [contentXmlHeader]
          (annotations.scope): "common-transit-convention-traders"
          securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
          responses:
            202:
              body:
                application/json:
                  description: JSON Payload
                  example: |
                    {
                      "_links": {
                        "self": {
                          "href": "/customs/transits/movements/arrivals/1/messages/2"
                        },
                        "arrival": {
                          "href": "/customs/transits/movements/arrivals/1"
                        }
                      },
                      "arrivalId": "1",
                      "messageId": "2",
                      "messageType": "IE044",
                      "body": "<CC044A>...</CC044A>"
                    }
        get:
          displayName: Get all messages that relate to a Movement Arrival
          description: |
            Get all the messages to do with a Movement Arrival. Any Movement Arrivals more than 28 days old will have been archived along with their related messages. Archived movements will return an HTTP 404 Not Found status.

            You may opt to filter this list of messages so that you only receive messages that have been received since a specified date and time.

            You will only be able to retrieve these messages if you have the correct Economic Operator Registration and Identification (EORI) number for that Movement Arrival.
          is:
            - headers.acceptHeader
            - acceptHeaderInvalid
          queryParameters:
            receivedSince:
              required: false
              type: datetime
              description: This is an optional filtering parameter. It allows you to request only the messages relating to a Movement Arrival which have been received since the date and time you have given us.
              example: 2021-06-21T09:00+00:00
          (annotations.scope): "common-transit-convention-traders"
          securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
          responses:
            200:
              body:
                application/json:
                  description: JSON Payload
                  example: |
                    {
                      "_links": {
                        "self": {
                          "href": "/customs/transits/movements/arrivals/1/messages"
                        }
                      },
                      "_embedded": {
                        "messages": [
                          {
                            "_links": {
                              "self": {
                                "href": "/customs/transits/movements/arrivals/1/messages/1"
                              },
                              "arrival": {
                                "href": "/customs/transits/movements/arrivals/1"
                              }
                            },
                            "arrivalId": "1",
                            "messageId": "1",
                            "received": "2020-12-12T12:12:15",
                            "messageType": "IE007",
                            "body": "<CC007A>...</CC007A>"
                          }
                        ],
                        "arrival": {
                          "id": "1",
                          "created": "2020-10-10T10:10:10",
                          "updated": "2020-12-12T12:12:12",
                          "movementReferenceNumber": "MRN",
                          "_links": {
                            "self": {
                              "href": "/customs/transits/movements/arrivals/1"
                            },
                            "messages": {
                              "href": "/customs/transits/movements/arrivals/1/messages"
                            }
                          }
                        }
                      }
                    }
            404:
              description: When the Movement Arrival does not exist, has been archived or is not available to the EORI number.
        /{messageId}:
          uriParameters:
            messageId:
              description: The message ID specifying the message to return
              type: string
              example: "1"
              required: true
          get:
            displayName: Get a message relating to a Movement Arrival and message ID
            description: |
             Get all messages relating to a specific Movement Arrival and message ID. For example, this could include messages about route diversions or unloading permissions. Any Movement Arrivals more than 28 days old will have been archived along with their related messages. Archived movements will return an HTTP 404 Not Found status.

              You will only be able to retrieve these messages if you have the correct Economic Operator Registration and Identification (EORI) number for that Movement Arrival.
            is:
              - headers.acceptHeader
              - acceptHeaderInvalid
            (annotations.scope): "common-transit-convention-traders"
            securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
            responses:
              200:
                body:
                  application/json:
                    description: JSON Payload
                    example: |
                      {
                        "_links": {
                          "self": {
                            "href": "/customs/transits/movements/arrivals/1/messages/1"
                          },
                          "arrival": {
                            "href": "/customs/transits/movements/arrivals/1"
                          }
                        },
                        "arrivalId": "1",
                        "messageId": "1",
                        "received": "2020-10-10T10:10:10",
                        "messageType": "IE007",
                        "body": "<CC007A>...</CC007A>"
                      }
              404:
                description: When a message does not exist, has been archived or is not available to the EORI number.
  /departures:
    post:
      displayName: Send a Declaration Data message
      description: |
        Send a Declaration Data message, to let the office at destination know that the goods are on their way. This notification will be sent when the goods leave the Office of Departure. It is also called an E_DEC_DAT (IE015).

        The response will contain a URI and departure ID for the Declaration Data. This will allow you to retrieve the submission status.

        The response will also contain an embedded requestId, boxId and boxName which will allow you to match this movement to any messages received via the Push Pull Notifications Service.

        If the user is not enrolled for an EORI number, they will receive an HTTP Forbidden Status.


      is: [contentXmlHeader]
      (annotations.scope): "common-transit-convention-traders"
      securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
      responses:
        202:
          body:
            application/json:
              description: JSON Payload
              example: |
                {
                  "_links": {
                    "self": {
                      "href": "/customs/transits/movements/departures/1"
                    }
                  },
                  "departureId": "1",
                  "messageType": "IE015",
                  "body": "<CC015B>...</CC015B>",
                  "_embedded":
                  {
                    "notifications":{
                      "boxId":"1234-5678-abcd-def",
                      "requestId":"/customs/transits/movements/departures/1",
                      "boxName":"customs/transits##1.0##notificationUrl"
                    }
                  }
                }
    get:
      displayName: Get all Movement Departures
      description: |
        You may opt to filter this list of Departures so that you only receive Movement Departures that have been updated since a specified date and time.

        Get all Movement Departures sent to the office at departure within 28 days of the goods being released at their final destination. Any movement more than 28 days old will have been archived along with their related messages. Archived Movements will return an HTTP 404 Not Found status.

        You will only be able to retrieve these messages if you have the correct Economic Operator Registration and Identification (EORI) number for that Movement Departure.

        **Note**: The 'movementReferenceNumber' field will only be populated when an MRN is allocated.
      is:
        - headers.acceptHeader
        - acceptHeaderInvalid
      queryParameters:
        updatedSince:
          required: false
          type: datetime
          description: This is an optional filtering parameter. It allows you to request only the Movement Departures which have been updated since the date and time you have given us.
          example: 2021-06-21T09:00+00:00
      (annotations.scope): "common-transit-convention-traders"
      securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
      responses:
        200:
          body:
            application/json:
              description: JSON Payload
              example: |
                {
                  "_links": {
                    "self": {
                      "href": "/customs/transits/movements/departures"
                    }
                  },
                  "_embedded": {
                    "departures": [
                      {
                        "id": "1",
                        "created": "2020-02-02T02:02:02",
                        "updated": "2020-02-02T02:02:02",
                        "movementReferenceNumber": "MRN",
                        "_links": {
                          "self": {
                            "href": "/customs/transits/movements/departures/1"
                          },
                          "messages": {
                            "href": "/customs/transits/movements/departures/1/messages"
                          }
                        }
                      },
                      {
                        "id": "2",
                        "created": "2020-02-04T02:02:02",
                        "updated": "2020-02-04T02:02:02",
                        "movementReferenceNumber": "MRN",
                        "_links": {
                          "self": {
                            "href": "/customs/transits/movements/departures/2"
                          },
                          "messages": {
                            "href": "/customs/transits/movements/departures/2/messages"
                          }
                        }
                      }
                    ],
                    "retrievedDepartures": 2,
                    "totalDepartures": 2
                  }
                }
    /{departureId}:
      get:
        displayName: Get a Movement Departure for a departure ID
        description: |
          Get a specific Movement Departure which was sent to the office at departure within 28 days of the goods being released at their final destination. Any Movements that are more than 28 days old will have been archived. Archived notifications will be return an HTTP 404 Not Found status.

          You will only be able to retrieve these messages if you have the EORI number associated with the Movement Departure.

          **Note**: The 'movementReferenceNumber' field will only be populated when an MRN is allocated.
        is:
          - headers.acceptHeader
          - acceptHeaderInvalid
        (annotations.scope): "common-transit-convention-traders"
        securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
        responses:
          200:
            body:
              application/json:
                description: JSON Payload
                example: |
                  {
                    "id": "1",
                    "created": "2020-10-10T10:10:10",
                    "updated": "2020-12-12T12:12:12",
                    "movementReferenceNumber": "MRN",
                    "_links": {
                      "self": {
                        "href": "/customs/transits/movements/departures/1"
                      },
                      "messages": {
                        "href": "/customs/transits/movements/departures/1/messages"
                      }
                    }
                  }

          404:
            description: When a Departure Movement does not exist, has been archived or is not available to the EORI number.
      /messages:
        post:
          displayName: Send a message related to a Movement Departure
          description: |
            Send a message to the office at destination. For example, a Declaration Cancellation request message, otherwise known as E_DEC_CAN (IE014), to let them know that the trader wants to cancel their Declaration Data message (IE015).

            The response will contain a URI and message ID for the message related to a Movement Departure. This will allow you to get the message status.

            If the user is not enrolled for an Economic Operator Registration and Identification number, they will receive an HTTP
          is: [contentXmlHeader]
          (annotations.scope): "common-transit-convention-traders"
          securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
          responses:
            202:
              body:
                application/json:
                  description: JSON Payload
                  example: |
                    {
                      "_links": {
                        "self": {
                          "href": "/customs/transits/movements/departures/1/messages/2"
                        },
                        "departure": {
                          "href": "/customs/transits/movements/departures/1"
                        }
                      },
                      "departureId": "1",
                      "messageId": "2",
                      "messageType": "IE014",
                      "body": "<CC014A>...</CC014A>"
                    }
        get:
          displayName: Get all messages relating to a Movement Departure
          description: |
            Get all messages sent within 28 days of the goods being released relating to a Movement Departure. Any Movements that are more than 28 days old will have been archived. Archived notifications will be return an HTTP 404 Not Found status.

            You may opt to filter this list of messages so that you only receive messages that have been received since a specified date and time.

            You will only be able to retrieve these messages if you have the EORI number associated with the Movement Departure.

            **Note**: The 'movementReferenceNumber' field will only be populated when an MRN is allocated.
          is:
            - headers.acceptHeader
            - acceptHeaderInvalid
          queryParameters:
            receivedSince:
              required: false
              type: datetime
              description: This is an optional filtering parameter. It allows you to request only the messages relating to a Movement Departure which have been received since the date and time you have given us.
              example: 2021-06-21T09:00+00:00
          (annotations.scope): "common-transit-convention-traders"
          securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
          responses:
            200:
              body:
                application/json:
                  description: JSON Payload
                  example: |
                    {
                      "_links": {
                        "self": {
                          "href": "/customs/transits/movements/departures/1/messages"
                        }
                      },
                      "_embedded": {
                        "messages": [
                          {
                            "_links": {
                              "self": {
                                "href": "/customs/transits/movements/departures/1/messages/1"
                              },
                              "departure": {
                                "href": "/customs/transits/movements/departures/1"
                              }
                            },
                            "departureId": "1",
                            "messageId": "1",
                            "received": "2020-12-12T12:12:15",
                            "messageType": "IE015",
                            "body": "<CC015B>...</CC015B>"
                          }
                        ],
                        "departure": {
                          "id": "1",
                          "created": "2020-10-10T10:10:10",
                          "updated": "2020-12-12T12:12:12",
                          "movementReferenceNumber": "MRN",
                          "_links": {
                            "self": {
                              "href": "/customs/transits/movements/departures/1"
                            },
                            "messages": {
                              "href": "/customs/transits/movements/departures/1/messages"
                            }
                          }
                        }
                      }
                    }
            404:
              description: When the movement does not exist, has been archived or is not available to the EORI number.
        /{messageId}:
          get:
            displayName: Get a message relating to a Movement Departure and message ID
            description: |
              Get all messages relating to a specific Movement Departure and message ID. For example, this could include declaration rejected or Movement Reference Number (MRN) allocated messages. Any messages more than 28 days old will be archived. Archived notifications will be return an HTTP 404 Not Found status.

              You will only be able to retrieve these messages if you have the EORI number associated with the Movement Departure.
            is:
              - headers.acceptHeader
              - acceptHeaderInvalid
            (annotations.scope): "common-transit-convention-traders"
            securedBy: [ sec.oauth_2_0: { scopes: [ "common-transit-convention-traders" ] } ]
            responses:
              200:
                body:
                  application/json:
                    description: JSON Payload
                    example: |
                      {
                        "_links": {
                          "self": {
                            "href": "/customs/transits/movements/departures/1/messages/1"
                          },
                          "departure": {
                            "href": "/customs/transits/movements/departures/1"
                          }
                        },
                        "departureId": "1",
                        "messageId": "1",
                        "received": "2020-10-10T10:10:10",
                        "messageType": "IE015",
                        "body": "<CC015B>...</CC015B>"
                      }
              404:
                description: When message does not exist, has been archived or is not available to the EORI number.
  /push-pull-notifications/box:
    get:
      displayName: Get Box Info
      description: |
        Get Box Information for the application if there is a push-pull-notification box
      is:
        - headers.acceptHeader
        - acceptHeaderInvalid
      (annotations.scope): "common-transit-convention-traders"
      securedBy: [ sec.x-application ]
      responses:
        200:
          body:
            application/json:
              description: JSON Payload
              example: |
                {
                    "boxId": "5fb4b568-b5ff-4475-bd29-0a3e70abb6d6",
                    "boxName": "customs/transits##1.0##notificationUrl",
                    "_links": {
                        "self": {
                            "href": "/customs/transits/movements/push-pull-notifications/box"
                        }
                    }
                }